# theme: jekyll-theme-minimal
title: MatsK's homepage
description: Bookmark this to keep an eye on my telephony project updates!
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
